### ISSUE TITLE
Begin block

### ISSUE THREAD

**Issue by michaeltyamada** [SnoozingPinata/MFAManager#1]
love the work and extended it for my needs. the example in the code triggers the begin block for each iteration. perhaps a better example is:

`$allEnabledUsers.UserPrincipalName |  Set-MFAMethodDefault -MFAType 'PhoneAppNotification'`

If you drop the requirement for the credential, it works well. A single prompt at first Begin block.

**Comment by SamuelMelton711** [comment]
Hey, I'm glad to hear it was useful! It definitely saved me a ton of time!

I checked over Microsoft's documentation on pipeline input [here.](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions?view=powershell-7.2#piping-objects-to-functions) Unless I'm mistaken, the begin block should only be executing once regardless of what's in your pipeline. 


At first, I thought you might be getting prompted multiple times because you aren't supplying the Credential object and it's marked mandatory (as you suggested), but I have written a test function to see how PowerShell operates in this scenario. In my test, PowerShell is behaving how I expect it to: it only prompts for the mandatory input once. You can see the test code below:

`function Test-Writer {`
`    param (`
`        [Parameter(`
`            Mandatory=$true,`
`            Position=0,`
`            ValueFromPipeline=$true)]`
`        [ValidateNotNull()]`
`        $MandatoryPipelineObject,`

`        [Parameter(`
`            Mandatory=$true,`
`            Position=1)]`
`        [ValidateNotNull()]`
`        [String]`
`        $MandatoryInputString`
`    )`

`    Begin {`
`        Write-Output "This is the Begin block. Mandatory Input String = $($MandatoryInputString)"`
`    }`

`    Process {`
`        Write-Output "This is the Process block. "`
`    }`
`}`

`1, 2, 3 | Test-Writer`

And the Output:

`Supply values for the following parameters:      `
`MandatoryInputString: my input here`
`This is the Begin block. Mandatory Input String = my input here`
`This is the Process block.`
`This is the Process block.`
`This is the Process block.`


Can you post the entirety of the code you used when you experienced the issue? That might help me get a better idea of what's going on in your scenario. If I'm not understanding, can you try rewording what the problem is?

Thank you,
Samuel

**Comment by SamuelMelton711** [comment]
Hey, I just came back to check on this and realized you were talking about the example within my function. I changed the example so that it doesn't prompt for every object in the pipeline. Thanks for the heads up!
